### PR TITLE
fix: mock_unsuccessful_command errors

### PR DESCRIPTION
**Pull request by matthewswl**
```ruby
    # Example :
      mock_unsuccessful_command(ExtinguishDebtAndLetterIt, errors: {
        entry: { not_found: "Couldn't find Entry with 'document_identifier'='foo'" }
      })

    # is equivalent to
      mock_command(ExtinguishDebtAndLetterIt,
        success: false,
        result: nil,
        errors: {:entry=>[code: :not_found, message: "Couldn't find Entry with 'document_identifier'='foo'"]},
      )
```

### CODE REVIEW

**Review by vlatkaswilich — APPROVED** [review]

**Review by guicharn — CHANGES_REQUESTED** [review]
Nice point, but this code is broken : 
```ruby
      mock_unsuccessful_command(ExtinguishDebtAndLetterIt, errors: {
        entry: { not_found: "Couldn't find Entry with 'document_identifier'='foo'" }
     })
```

We need to update `#mock_unsuccessful_command` to keep the feature.

**Comment by matthewswl** [comment]
> Nice point, but this code is broken :
> 
> ```ruby
>       mock_unsuccessful_command(ExtinguishDebtAndLetterIt, errors: {
>         entry: { not_found: "Couldn't find Entry with 'document_identifier'='foo'" }
>      })
> ```
> 
> We need to update `#mock_unsuccessful_command` to keep the feature.

According to the documentation the correct use of `mock_unsuccessful_command` is:

```ruby
mock_unsuccessful_command(CollectionChecker,
   errors: { collection: [ empty:  "Your collection is empty !" ] }
 )
```

which would give:

```ruby
mock_unsuccessful_command(ExtinguishDebtAndLetterIt,
  errors: { entry: [ not_found: "Couldn't find Entry with 'document_identifier'='foo'" ] }
)
```

for you example.

**Comment by guicharn** [comment]
It seems to have a mistake in the documentation. 😞 
The goal (and use in most of code) is to have : 
```ruby
entry: { not_found: "Couldn't find Entry with 'document_identifier'='foo'" }
```

**Comment by matthewswl** [comment]
@guicharn It does make sense though?

https://api.rubyonrails.org/v5.1.7/classes/ActiveModel/Errors.html

```ruby
person.errors.details
# => {:name=>[{error: :not_implemented}, {error: :invalid}]}
```

**Comment by guicharn** [comment]
In the code, there is this example.
```ruby
      mock_unsuccessful_command(ExtinguishDebtAndLetterIt, errors: {
        entry: { not_found: "Couldn't find Entry with 'document_identifier'='foo'" }
      })

      # is equivalent to
      mock_command(ExtinguishDebtAndLetterIt,
        success: false,
        result: nil,
        errors: {:entry=>[code: :not_found, message: "Couldn't find Entry with 'document_identifier'='foo'"]},
      )
```
The goal of `#mock_unsuccessful_command` is to provide more concise method call to mock errors.


`command.errors` must return : 
```ruby
{
  entry: [  { code: :not_found, message: "Couldn't find Entry with 'document_identifier'='foo'" } ]
}
```
This implementation has been made to simplify the work with errors.

`Command` does not manage errors like Rails.

If we use the Rails specification, we need to access to `person.errors.details` to access to `{:name=>[{error: :not_implemented}, {error: :invalid}]}` and we need to parse this hash of array of hashes to access codes.
And to access messages, we must use `person.errors.messages` to give `{:name=>["is invalid", "must be implemented"]}`, and parse it.
And there are no real correlation between this 2 objects, to match code with message.
So we have made the choice to have a simplier object to manage errors.
We keep `:code` and `:message` as keys to be more "compatible" with many apps, which already used this format before we create the gem (personally, I would have preferred not to have them).

Extra, this format is useful to render error details in controller, according to the guild specification.

If you need to inject Rails model errors in an instance of Command, you can use `errors.merge_from(my_instance_of_model)`

**Comment by matthewswl** [comment]
@guicharn Got it! I fixed the PR!

**Pull request merged**
